############################
# Prefix
############################

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

############################
# Reload config
############################

bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

############################
# Split panes
############################

unbind %
unbind '"'

# Vertical (izquierda | derecha)
bind / split-window -h

# Horizontal (arriba / abajo)
bind - split-window -v

############################
# Pane navigation
############################

bind Left  select-pane -L
bind Down  select-pane -D
bind Up    select-pane -U
bind Right select-pane -R

############################
# Mouse
############################

set -g mouse on

############################
# History
############################

set -g history-limit 100000

############################
# Faster Escape
############################

set -sg escape-time 0

############################
# Status bar
############################

set -g status-position bottom
set -g status-interval 5

set -g status-style "bg=#1e1e2e,fg=#cdd6f4"

set -g status-left-length 30
set -g status-right-length 100

set -g status-left "#[fg=#89b4fa,bold]#S "

set -g status-right "#[fg=#a6adc8]%Y-%m-%d #[fg=#89b4fa]%H:%M "

set -g window-status-format " #I "
set -g window-status-current-format "#[fg=#1e1e2e,bg=#89b4fa,bold] #I "



set -g status off
